#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / "manifests/kde-tier2-package-contracts.json"
TIER2 = ROOT / "manifests/kde-frameworks-tier2.json"
CI_MAINTAINER = "SupraLINUX Build System <build@supralinux.invalid>"
VCS_GIT = "https://github.com/SupraLINUX/SupraLINUX.git -b architecture/bootstrap-v1"
VCS_BROWSER = "https://github.com/SupraLINUX/SupraLINUX/tree/architecture/bootstrap-v1"
PYTHON_BUILD_DEPS = [
    "dh-sequence-python3",
    "libpyside6-dev",
    "libshiboken6-dev",
    "python3-build",
    "python3-dev",
    "python3-setuptools",
    "python3-wheel",
]


def load(path: Path):
    return json.loads(path.read_text())


def spans(lines: list[str]):
    result = {}
    starts = []
    for i, line in enumerate(lines):
        if line and not line[0].isspace() and ":" in line:
            starts.append((i, line.split(":", 1)[0]))
    for pos, (start, name) in enumerate(starts):
        end = starts[pos + 1][0] if pos + 1 < len(starts) else len(lines)
        result[name] = (start, end)
    return result


def field_value(lines: list[str], name: str):
    s = spans(lines).get(name)
    if not s:
        return None
    start, end = s
    first = lines[start].split(":", 1)[1].strip()
    rest = [line.strip() for line in lines[start + 1 : end]]
    return " ".join([first, *rest]).strip()


def set_field(lines: list[str], name: str, value: str):
    mapping = spans(lines)
    replacement = [f"{name}: {value}"]
    if name in mapping:
        start, end = mapping[name]
        lines[start:end] = replacement
    else:
        lines.extend(replacement)


def remove_field(lines: list[str], name: str):
    mapping = spans(lines)
    if name in mapping:
        start, end = mapping[name]
        del lines[start:end]


def set_build_depends(lines: list[str], additions: list[str]):
    current = field_value(lines, "Build-Depends")
    if current is None:
        raise SystemExit("debian/control lacks Build-Depends")
    deps = [x.strip() for x in current.split(",") if x.strip()]
    present_names = {re.split(r"\s|\(", dep, maxsplit=1)[0] for dep in deps}
    for dep in additions:
        if dep not in present_names:
            deps.append(dep)
    rendered = "Build-Depends: " + deps[0]
    if len(deps) > 1:
        rendered += ",\n" + "\n".join(
            "               " + dep + ("," if i < len(deps) - 1 else "")
            for i, dep in enumerate(deps[1:], start=1)
        )
    mapping = spans(lines)
    start, end = mapping["Build-Depends"]
    lines[start:end] = rendered.splitlines()


def modify_control(path: Path, node: dict):
    text = path.read_text()
    paragraphs = re.split(r"\n\s*\n", text.strip())
    if not paragraphs:
        raise SystemExit("empty debian/control")
    source_lines = paragraphs[0].splitlines()
    original_maintainer = field_value(source_lines, "Maintainer")
    if not original_maintainer:
        raise SystemExit("debian/control lacks Maintainer")
    remove_field(source_lines, "Uploaders")
    set_field(source_lines, "Maintainer", CI_MAINTAINER)
    set_field(source_lines, "Vcs-Git", VCS_GIT)
    set_field(source_lines, "Vcs-Browser", VCS_BROWSER)
    # Add this last so no later source-field rewrite can consume it as part of
    # a preceding multi-line field span.
    set_field(source_lines, "XSBC-Original-Maintainer", original_maintainer)

    python_module = node.get("python_module")
    if python_module:
        set_build_depends(source_lines, PYTHON_BUILD_DEPS)

    paragraphs[0] = "\n".join(source_lines)
    if python_module:
        pkg = node["supralinux_additional_binary_packages"][0]
        runtime = node["python_runtime_package"]
        if any(re.search(rf"^Package:\s*{re.escape(pkg)}\s*$", p, re.M) for p in paragraphs[1:]):
            raise SystemExit(f"Python package already exists in technical reference: {pkg}")
        paragraphs.append(
            "\n".join(
                [
                    f"Package: {pkg}",
                    "Section: python",
                    "Architecture: any",
                    f"Depends: {runtime} (= " + "$" + "{binary:Version}),",
                    "         " + "$" + "{misc:Depends},",
                    "         " + "$" + "{python3:Depends},",
                    "         " + "$" + "{shlibs:Depends},",
                    f"Description: Python bindings for {python_module}",
                    f" Python 3 bindings generated by KDE upstream for {python_module}.",
                    " .",
                    " This package is provided by SupraLINUX because the upstream Linux",
                    " profile enables these bindings and the technical Debian reference",
                    " disables them.",
                ]
            )
        )
        install = path.parent / f"{pkg}.install"
        install.write_text(f"usr/lib/python3/dist-packages/{python_module}*.so\n")

    path.write_text("\n\n".join(paragraphs) + "\n")


def cmake_flags(profile: dict) -> list[str]:
    flags = []
    for key, value in profile.items():
        if key == "BUILD_QML_IF_PROVIDER_AVAILABLE":
            continue
        if not isinstance(value, bool):
            continue
        flags.append(f"-D{key}={'ON' if value else 'OFF'}")
    return flags


def modify_rules(path: Path, profile: dict):
    text = path.read_text()
    flags = cmake_flags(profile)
    for flag in flags:
        key = flag.split("=", 1)[0]
        text = re.sub(rf"{re.escape(key)}=(?:ON|OFF)", flag, text)

    missing = [flag for flag in flags if flag not in text]
    if missing:
        lines = text.splitlines()
        inserted = False
        for i, line in enumerate(lines):
            if re.match(r"^\s*dh_auto_configure\b", line):
                if " -- " in line:
                    lines[i] = line + " " + " ".join(missing)
                else:
                    lines[i] = line + " -- " + " ".join(missing)
                inserted = True
                break
        if not inserted:
            lines += ["", "override_dh_auto_configure:", "\tdh_auto_configure -- " + " ".join(missing)]
        text = "\n".join(lines) + "\n"

    path.write_text(text)


def prepend_changelog(path: Path, source_package: str, version: str):
    old = path.read_text()
    entry = (
        f"{source_package} ({version}) UNRELEASED; urgency=medium\n\n"
        "  * Materialize SupraLINUX packaging from KDE upstream source and the\n"
        "    pinned Debian packaging tree used only as a technical reference.\n"
        "  * Preserve upstream-selected Linux features.\n\n"
        f" -- {CI_MAINTAINER}  Sun, 20 Sep 2026 00:00:00 +0000\n\n"
    )
    path.write_text(entry + old)


def append_readme(path: Path):
    note = (
        "\n\n## SupraLINUX materialization\n\n"
        "This tree is generated from the authoritative KDE Frameworks 6.30.0 "
        "source plus a SHA-256-pinned Debian packaging tree used only as a "
        "technical reference. Debian/Ubuntu do not define the selected KDE "
        "feature profile. The CI maintainer address uses the reserved .invalid "
        "TLD and must be replaced by an approved SupraLINUX project contact "
        "before repository publication.\n"
    )
    if path.exists():
        text = path.read_text()
        if "## SupraLINUX materialization" not in text:
            path.write_text(text.rstrip() + note)
    else:
        path.write_text("# Source packaging notes" + note)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--node", required=True)
    parser.add_argument("--source-root", required=True)
    args = parser.parse_args()

    contracts = load(CONTRACTS)
    tier2 = load(TIER2)
    if contracts.get("state") not in {"reference-capture-pass", "materialized"}:
        raise SystemExit("package-contract state is not materializable")
    if contracts.get("materialization", {}).get("status") not in {"pending-ci", "PASS"}:
        raise SystemExit("unsupported materialization state")
    if args.node not in contracts.get("selected_nodes", []):
        raise SystemExit(f"node not selected for materialization: {args.node}")

    node = contracts["nodes"][args.node]
    canonical = {n["id"]: n for n in tier2["nodes"]}[args.node]
    if canonical.get("source_sha256") != node.get("source_sha256"):
        raise SystemExit("source authority SHA drift")
    if canonical.get("planning", {}).get("readiness") not in {"package-contract-ready", "build-ready"}:
        raise SystemExit("node is not materialization/build ready")
    if canonical.get("planning", {}).get("package_contract") not in {"not-materialized", "materialized"}:
        raise SystemExit("node package-contract state is not compatible with materialization")

    root = Path(args.source_root)
    debian = root / "debian"
    for required in (debian / "control", debian / "rules", debian / "changelog", debian / "source" / "format"):
        if not required.exists():
            raise SystemExit(f"missing technical reference file: {required}")

    modify_control(debian / "control", node)
    modify_rules(debian / "rules", node["selected_profile"])
    prepend_changelog(debian / "changelog", node["source_package"], node["package_version_candidate"])
    append_readme(debian / "README.source")

    metadata = {
        "schema": 1,
        "node": args.node,
        "source_authority": "kde-upstream",
        "upstream_version": node["upstream_version"],
        "upstream_source_sha256": node["source_sha256"],
        "technical_reference": {
            "provider": "debian-sid",
            "version": node["technical_references"]["debian"]["version"],
            "debian_tar_sha256": node["technical_references"]["debian"]["debian_tar_sha256"],
        },
        "package_version": node["package_version_candidate"],
        "selected_profile": node["selected_profile"],
        "python_module": node.get("python_module"),
        "generated_maintainer": CI_MAINTAINER,
        "package_state_effect": "none",
    }
    (debian / "supralinux-materialization.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(json.dumps(metadata, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
