#!/usr/bin/env python3
"""Render the current status from live manifests, without changing evidence."""
import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    def load(name):
        return json.loads((ROOT / "manifests" / name).read_text())
    desktop = load("desktop-stack.json")
    plasma = load("kde-plasma.json")
    level0 = load("kde-plasma-level0.json")
    dag = load("kde-dag.json")
    certification = load("authoritative-kvm-certification.json")
    checkpoints = load("execution-checkpoints.json")
    counts = Counter(node.get("state", "pending") for node in dag["nodes"].values())
    planning = plasma["planning"]
    lines = ["# Current SupraLINUX status", "",
             "Generated by `python3 scripts/render-project-status.py`. Edit the live manifests first.", "",
             "| Item | Current state |", "| --- | --- |",
             f"| Platform | Ubuntu {desktop['platform']['version']} / {desktop['platform']['series']} |",
             f"| KDE selection | Plasma {desktop['desktop']['plasma']['version']} / Frameworks {desktop['desktop']['frameworks']['version']} / Gear {desktop['desktop']['gear']['version']} |",
             f"| Qt provider | {desktop['qt']['provider']['candidate_version']}; certification {desktop['qt']['certification']['status']} |",
             f"| Frameworks build evidence | {counts.get('PASS', 0)} PASS; scope is recorded per DAG node |",
             f"| KVM infrastructure | {certification['next_gate']} |",
             f"| Plasma phase | {planning['phase']} / {planning['status']} |",
             f"| Next gate | {planning['next_gate']} |",
             f"| Level 0 | {level0['selected_node_count']} nodes; {level0['state']} |",
             f"| Plasma package execution | authorized={str(planning['package_execution_authorized']).lower()} |",
             f"| Frameworks milestone | {checkpoints['checkpoints']['frameworks-6.30-pass']['state']}; execution cache |",
             "", "Sources: `manifests/desktop-stack.json`, `manifests/kde-dag.json`,",
             "`manifests/authoritative-kvm-certification.json`, `manifests/kde-plasma.json`,",
             "`manifests/kde-plasma-level0.json`, `manifests/execution-checkpoints.json`.", "",
             "A cache PASS does not upgrade the scope of the builds it contains.",
             "Historical evidence remains valid for its original inputs and environment.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/status/current.md"
    expected = render()
    if args.check:
        if not path.is_file() or path.read_text() != expected:
            raise SystemExit("Current status is stale; run python3 scripts/render-project-status.py")
        print("Current project status: PASS")
    else:
        path.write_text(expected)


if __name__ == "__main__":
    main()
