#!/usr/bin/env python3
"""Render the current status from live manifests, without changing evidence."""
import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    def load(name):
        return json.loads((ROOT / "manifests" / name).read_text())
    desktop = load("desktop-stack.json")
    plasma = load("kde-plasma.json")
    level0 = load("kde-plasma-level0.json")
    materialization = load("kde-plasma-level0-materialization.json")
    dag = load("kde-dag.json")
    certification = load("authoritative-kvm-certification.json")
    checkpoints = load("execution-checkpoints.json")
    counts = Counter(node.get("state", "pending") for node in dag["nodes"].values())
    packages = load("kde-plasma-package-build.json")
    revalidation = load('package-revalidation.json')
    planning = plasma["planning"]
    hold = packages.get('dependency_hold')
    next_gate = 'authoritative-package-revalidation:' + hold['node'] if hold else planning['next_gate']
    if not hold and packages['authorized_nodes']:
        next_gate = 'authoritative-plasma-package-build:' + ','.join(packages['authorized_nodes'])
    if not hold and packages['authorized_nodes'] and packages.get('execution_mode') == 'preflight':
        next_gate = 'authoritative-plasma-package-input-preflight:' + ','.join(packages['authorized_nodes'])
    providers = {name: node for name, node in packages['nodes'].items() if node.get('source_scope') == 'plasma-supplementary-provider'}
    components = {name: node for name, node in packages['nodes'].items() if name not in providers}
    compatibility_holds = ', '.join(name + ': ' + node['compatibility_hold']['reason']
                                    for name, node in components.items() if node.get('compatibility_hold'))
    lines = ["# Current SupraLINUX status", "",
             "Generated by `python3 scripts/render-project-status.py`. Edit the live manifests first.", "",
             "| Item | Current state |", "| --- | --- |",
             f"| Platform | Ubuntu {desktop['platform']['version']} / {desktop['platform']['series']} |",
             f"| KDE selection | Plasma {desktop['desktop']['plasma']['version']} / Frameworks {desktop['desktop']['frameworks']['version']} / Gear {desktop['desktop']['gear']['version']} |",
             f"| Qt provider | {desktop['qt']['provider']['candidate_version']}; certification {desktop['qt']['certification']['status']} |",
             f"| Frameworks build evidence | {counts.get('PASS', 0)} PASS; scope is recorded per DAG node |",
             f"| KVM infrastructure | {certification['next_gate']} |",
             f"| Plasma phase | {planning['phase']} / {planning['status']} |",
             f"| Next gate | {next_gate} |",
             f"| Level 0 | {level0['selected_node_count']} nodes; {level0['state']} |",
             f"| Level 0 source materialization | {materialization['state']}; {materialization.get('evidence', {}).get('counts', {}).get('PASS', 0)} verified sources |",
             f"| Plasma package execution | authorized={str(packages['package_execution_authorized']).lower()} |",
             f"| Authorized Plasma nodes | {', '.join(packages['authorized_nodes']) or 'none'} |",
             f"| Plasma dependency hold | {hold['reason'] if hold else 'none'} |",
             f"| Plasma compatibility reviews | {compatibility_holds or 'none'} |",
             f"| Reviewed Plasma packages | {', '.join(name + ': ' + node['state'] for name, node in components.items())} |",
             f"| Reviewed supplementary providers | {', '.join(name + ' ' + node['version'] + ': ' + node['state'] for name, node in providers.items()) or 'none'} |",
             f"| Plasma package Attempts | {', '.join(name + ': ' + str(len(node['attempts'])) + '; last ' + (node['attempts'][-1]['state'] if node['attempts'] else 'none') for name, node in packages['nodes'].items())} |",
             f"| Frameworks milestone | {checkpoints['checkpoints']['frameworks-6.30-pass']['state']}; execution cache |",
             f"| Frameworks predecessor repairs | {', '.join(name + ' ' + record['version'] + ': ' + record['state'] for name, record in revalidation['nodes'].items())} |",
             "", "Sources: `manifests/desktop-stack.json`, `manifests/kde-dag.json`,",
             "`manifests/authoritative-kvm-certification.json`, `manifests/kde-plasma.json`,",
             "`manifests/kde-plasma-level0.json`, `manifests/kde-plasma-level0-materialization.json`,",
             "`manifests/execution-checkpoints.json`, `manifests/package-revalidation.json`.", "",
             "A cache PASS does not upgrade the scope of the builds it contains.",
             "Historical evidence remains valid for its original inputs and environment.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/status/current.md"
    expected = render()
    if args.check:
        if not path.is_file() or path.read_text() != expected:
            raise SystemExit("Current status is stale; run python3 scripts/render-project-status.py")
        print("Current project status: PASS")
    else:
        path.write_text(expected)


if __name__ == "__main__":
    main()
