#!/usr/bin/env python3
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
def load(p): return json.loads((ROOT/p).read_text())
def req(v,m):
    if not v:
        print("ERROR:",m,file=sys.stderr); raise SystemExit(1)

M=load("manifests/kde-tier3-kio-round22-diagnostic.json")
R21=load("manifests/kde-tier3-kio-round21-diagnostic.json")
T=load("manifests/kde-frameworks-tier3.json")
L=load("manifests/kde-tier3-build-level1.json")
C=load("manifests/kde-tier3-package-contracts.json")
MAT=load("manifests/kde-tier3-materialization.json")
W=(ROOT/".github/workflows/kde-tier3-kio-round22-diagnostic.yml").read_text()
ROUTER=(ROOT/".github/workflows/pr-ci-router.yml").read_text()
RUNNER=(ROOT/"scripts/run-kde-tier3-kio-round22-diagnostic.sh").read_text()
DOC=(ROOT/"docs/kde-tier3-kio-round22-diagnostic.md").read_text()

req(M.get("schema")==1 and M.get("node")=="kio" and M.get("round")==22,"Round22 identity")
req(M.get("authority")=="kde-upstream" and M.get("frameworks_series")=="6.30.0" and M.get("upstream_ref")=="v6.30.0","Round22 upstream")
req(M.get("claim")=="non-promoting-krecent-ctest-home-matrix-diagnostic" and M.get("non_promoting") is True,"Round22 claim")
req(M.get("package_attempted") is False and M.get("package_state_effect")=="none" and M.get("package_revision_allocation") is False,"Round22 package safety")
req(M.get("canonical_source_modified") is False and M.get("diagnostic_worktree_modified") is True and M.get("test_suppression") is False,"Round22 source safety")
req(M.get("execution_authorized") is True and M.get("package_execution_authorized") is False and M.get("status")=="definition-pending-diagnostic","Round22 authorization")
req(M.get("canonical_snapshot")=="12 PASS / 1 pending / 1 current FAIL / 6 BLOCKED","Round22 snapshot")
p=M.get("predecessor_round21",{})
req(R21.get("status")=="diagnostic-PASS" and R21.get("next_gate")=="tier3-round22-kio-krecent-ctest-home-matrix-diagnostic-definition","Round21 closed handoff")
req(p.get("workflow_run")==36248969228 and p.get("job_id")==108423337171 and p.get("artifact_id")==10908497619,"Round22 predecessor evidence")
req(p.get("artifact_sha256")=="31f4fddc17bf13b2058773c9c506a54f625ebe100d884418ef27fe45fd9ec4e0","Round22 predecessor digest")
req(p.get("environment_valid") is True and p.get("baseline_failures")==0 and p.get("capture_all_duplicate_modified_groups")==0,"Round22 predecessor result")
a=M.get("attempt8_reference",{})
req(a.get("working_directory")=="/build/reproducible-path/kf6-kio-6.30.0/obj-x86_64-linux-gnu/autotests","Round22 Attempt8 CWD")
outer=a.get("outer_test_environment",{})
req(outer.get("home").endswith("/debian/.supralinux-test-home/sbuild"),"Round22 hidden HOME")
req(outer.get("lang")=="C.UTF-8" and outer.get("lc_all")=="C.UTF-8" and outer.get("logname")=="sbuild" and outer.get("user")=="sbuild","Round22 sbuild identity")
req(outer.get("qt_qpa_platform")=="xcb" and outer.get("qt_qpa_system_icon_theme")=="breeze","Round22 Qt display env")
matrix=M.get("diagnostic_matrix",[])
req([x.get("id") for x in matrix]==["direct-visible","direct-hidden","ctest-visible","ctest-hidden"],"Round22 matrix ids")
req(all(x.get("repetitions")==30 for x in matrix),"Round22 repetitions")
vc=M.get("validity_contract",{})
req(vc.get("source_and_build_path_zero_dot_prefixed_components") is True and vc.get("test_working_directory_zero_dot_prefixed_components") is True,"Round22 visible source/CWD")
req(vc.get("xbel_capture_instrumentation","").startswith("copy m_xbelPath immediately"),"Round22 XBEL capture semantics")
policy=T.get("discovery_policy",{})
req(policy.get("phase")=="diagnostic" and policy.get("package_builds")=="tier3-round22-diagnostic-pending","Round22 live phase")
req(policy.get("remediation")=="round22-kio-krecent-ctest-home-matrix-diagnostic-pending-ci","Round22 live marker")
gate="tier3-round22-kio-krecent-ctest-home-matrix-diagnostic-evidence"
for obj,name in ((T.get("active_remediation",{}),"canonical"),(L.get("active_remediation",{}),"Level1"),(C.get("active_remediation",{}),"contracts"),(MAT.get("active_remediation",{}),"materialization")):
    req(obj.get("next_gate")==gate,name+" Round22 gate")
req(T.get("active_remediation",{}).get("execution_authorized") is False and L.get("execution_authorized") is False and L.get("state")=="attempt8-closed-mixed" and L.get("current_attempt")==8,"Attempt9 remains unauthorized")
for token in ("workflow_call","run-kde-tier3-kio-round22-diagnostic.sh","KIO Round 22 KRecent CTest/HOME matrix"): req(token in W,"workflow "+token)
req("pull_request:" not in W,"Round22 workflow must be reusable-only")
for token in ("run_round22","kde-tier3-kio-round22-diagnostic.yml","tier3-round22-diagnostic-pending"): req(token in ROUTER,"router "+token)
for token in ("SUPRALINUX_CAPTURE_XBEL","ctest --verbose -R","direct-visible","direct-hidden","ctest-visible","ctest-hidden","LANG=C.UTF-8","LC_ALL=C.UTF-8","dbus-run-session","xvfb-run"): req(token in RUNNER,"runner "+token)
for forbidden in ("dpkg-buildpackage","sbuild --"): req(forbidden not in RUNNER,"Round22 must not package "+forbidden)
req("Attempt 8" in DOC and "CTest" in DOC and "HOME" in DOC and "Attempt 9" in DOC,"Round22 docs")
req(M.get("next_gate")==gate and M.get("stable_promotion_requires_explicit_user_approval") is True,"Round22 gate/stable policy")
print("KDE Tier 3 KIO Round 22 diagnostic definition: PASS")
print("matrix=direct-visible,direct-hidden,ctest-visible,ctest-hidden")
print("Attempt9=NOT-AUTHORIZED")
