#!/usr/bin/env python3
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
def load(p): return json.loads((ROOT/p).read_text())
def req(v,m):
    if not v:
        print("ERROR:",m,file=sys.stderr)
        raise SystemExit(1)

M=load("manifests/kde-tier3-kio-round20-diagnostic.json")
R19=load("manifests/kde-tier3-kio-round19-diagnostic.json")
T=load("manifests/kde-frameworks-tier3.json")
L=load("manifests/kde-tier3-build-level1.json")
C=load("manifests/kde-tier3-package-contracts.json")
MAT=load("manifests/kde-tier3-materialization.json")
W=(ROOT/".github/workflows/kde-tier3-kio-round20-diagnostic.yml").read_text()
ROUTER=(ROOT/".github/workflows/pr-ci-router.yml").read_text()
RUNNER=(ROOT/"scripts/run-kde-tier3-kio-round20-diagnostic.sh").read_text()
DOC=(ROOT/"docs/kde-tier3-kio-round20-diagnostic.md").read_text()

req(M.get("schema")==1 and M.get("node")=="kio" and M.get("round")==20,"Round20 identity")
req(M.get("authority")=="kde-upstream" and M.get("frameworks_series")=="6.30.0" and M.get("upstream_ref")=="v6.30.0","Round20 upstream identity")
req(M.get("claim")=="non-promoting-kio-environment-corrected-residual-test-diagnostic" and M.get("non_promoting") is True,"Round20 claim")
req(M.get("package_attempted") is False and M.get("package_state_effect")=="none","Round20 package state")
req(M.get("canonical_source_modified") is False and M.get("diagnostic_worktree_modified") is True,"Round20 source safety")
req(M.get("dag_state_changes_allowed") is False and M.get("downstream_eligibility_changes_allowed") is False,"Round20 DAG safety")
req(M.get("package_revision_allocation") is False and M.get("test_suppression") is False,"Round20 no revision/suppression")
req(M.get("execution_authorized") is True and M.get("package_execution_authorized") is False,"Round20 diagnostic-only authorization")
req(M.get("status")=="definition-pending-diagnostic","Round20 definition lifecycle")
req(M.get("canonical_snapshot")=="12 PASS / 1 pending / 1 current FAIL / 6 BLOCKED","Round20 canonical snapshot")
req(M.get("canonical_kio")=={"state":"FAIL","package_version":"6.30.0-0supralinux8","downstream_eligible":False},"Round20 canonical KIO")
p19=M.get("predecessor_round19",{})
req(R19.get("status")=="diagnostic-PASS" and R19.get("next_gate")=="tier3-round20-kio-environment-corrected-diagnostic-definition","Round19 closed handoff")
req(p19.get("workflow_run")==36243076879 and p19.get("job_id")==108407192850 and p19.get("artifact_id")==10906951441,"Round20 Round19 evidence identity")
req(p19.get("artifact_sha256")=="3395536506ea205ce722a4a9be8962b0f0b3fb7597dbee708a6b7e0dc8ef2611","Round20 Round19 artifact digest")
req(len(p19.get("defects",[]))==2,"Round20 methodology defect ledger")
sm=M.get("source_materialization",{})
req(sm.get("artifact_id")==10898999142 and sm.get("artifact_sha256")=="c31aafa0d5718a0e8287212b49f35022a58a5519a87a04991424939284d9003d","Round20 source materialization")
req(sm.get("package_version")=="6.30.0-0supralinux8","Round20 unchanged KIO revision")
vc=M.get("corrected_validity_contract",{})
recent=vc.get("krecentdocument",{})
req(recent.get("required_directories")==["$HOME/.qttest/share","$HOME/.qttest/config"],"Round20 KRecent QStandardPaths parents")
req(recent.get("xbel_path")=="$HOME/.qttest/share/recently-used.xbel","Round20 KRecent XBEL path")
kdir=vc.get("kdirmodel",{})
req(kdir.get("visible_home")=="$RUNNER_TEMP/supralinux-kdir-home/sbuild" and kdir.get("visible_home_must_have_zero_dot_prefixed_components") is True,"Round20 truly-visible HOME")
req(kdir.get("selected_test_functions")==["testShowRoot","testShowRootWithTrailingSlash","testShowRootAndExpandToUrl"],"Round20 exact KDir tests")
scope=M.get("diagnostic_scope",{})
req(scope.get("krecentdocument",{}).get("baseline_repetitions")==30 and scope.get("krecentdocument",{}).get("delayed_repetitions")==30,"Round20 KRecent repetitions")
req(scope.get("kdirmodel",{}).get("sequence")==["hidden-home-initial","truly-visible-home","hidden-home-repeat"],"Round20 KDir A/B/A")
req(scope.get("kdirmodel",{}).get("visible_path_audit_required") is True,"Round20 visible path audit")
policy=T.get("discovery_policy",{})
req(policy.get("phase")=="diagnostic" and policy.get("package_builds")=="tier3-round20-diagnostic-pending","Round20 live phase")
req(policy.get("remediation")=="round20-kio-environment-corrected-diagnostic-pending-ci","Round20 live marker")
for obj,name in ((T.get("active_remediation",{}),"canonical"),(L.get("active_remediation",{}),"Level1"),(C.get("active_remediation",{}),"contracts"),(MAT.get("active_remediation",{}),"materialization")):
    req(obj.get("next_gate")=="tier3-round20-kio-environment-corrected-diagnostic-evidence",name+" Round20 evidence gate")
req(T.get("active_remediation",{}).get("execution_authorized") is False,"Round20 canonical package execution paused")
req(L.get("execution_authorized") is False and L.get("state")=="attempt8-closed-mixed","Round20 Attempt8 remains closed")
req(L.get("current_attempt")==8,"Round20 current attempt remains 8")
for token in ("workflow_call","run-kde-tier3-kio-round20-diagnostic.sh","KIO Round 20 environment-corrected residual diagnostic"):
    req(token in W,f"Round20 workflow token {token}")
req("pull_request:" not in W,"Round20 reusable workflow must not subscribe directly to PR")
for token in ("run_round20","kde-tier3-kio-round20-diagnostic.yml","tier3-round20-diagnostic-pending"):
    req(token in ROUTER,f"Round20 router token {token}")
for token in (".qttest/share",".qttest/config","recent-capture-all","QTest::qWait(5)","RUNNER_TEMP","kdir-visible-path-audit.json","testShowRootWithTrailingSlash"):
    req(token in RUNNER,f"Round20 runner token {token}")
for forbidden in ("dpkg-buildpackage","sbuild --"):
    req(forbidden not in RUNNER,f"Round20 must not package: {forbidden}")
req("Round 19" in DOC and "QStandardPaths" in DOC and "truly visible" in DOC and "Attempt 9" in DOC,"Round20 documentation")
req(M.get("next_gate")=="tier3-round20-kio-environment-corrected-diagnostic-evidence","Round20 evidence gate")
req(M.get("stable_promotion_requires_explicit_user_approval") is True,"stable approval")
print("KDE Tier 3 KIO Round 20 diagnostic definition: PASS")
print("canonical=12 PASS / 1 pending / 1 current FAIL / 6 BLOCKED")
print("KIO=FAIL 6.30.0-0supralinux8")
print("Attempt9=NOT-AUTHORIZED")
print("next_gate="+M["next_gate"])
