#!/usr/bin/env python3
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
def load(p): return json.loads((ROOT/p).read_text())
def req(v,m):
    if not v:
        print("ERROR:",m,file=sys.stderr); raise SystemExit(1)
M=load("manifests/kde-tier3-kio-round23-diagnostic.json")
R22=load("manifests/kde-tier3-kio-round22-diagnostic.json")
T=load("manifests/kde-frameworks-tier3.json")
L=load("manifests/kde-tier3-build-level1.json")
C=load("manifests/kde-tier3-package-contracts.json")
MAT=load("manifests/kde-tier3-materialization.json")
W=(ROOT/".github/workflows/kde-tier3-kio-round23-diagnostic.yml").read_text()
ROUTER=(ROOT/".github/workflows/pr-ci-router.yml").read_text()
RUNNER=(ROOT/"scripts/run-kde-tier3-kio-round23-diagnostic.sh").read_text()
HOOK=(ROOT/"scripts/run-kde-tier3-kio-round23-hook.sh").read_text()
DOC=(ROOT/"docs/kde-tier3-kio-round23-diagnostic.md").read_text()
req(M.get("schema")==1 and M.get("round")==23 and M.get("node")=="kio","Round23 identity")
req(M.get("authority")=="kde-upstream" and M.get("frameworks_series")=="6.30.0","Round23 upstream")
req(M.get("claim")=="non-promoting-krecent-attempt8-rootfs-diagnostic" and M.get("non_promoting") is True,"Round23 claim")
req(M.get("package_attempted") is False and M.get("package_state_effect")=="none" and M.get("package_revision_allocation") is False,"Round23 package safety")
req(M.get("execution_authorized") is True and M.get("package_execution_authorized") is False,"Round23 authorization")
attempts=M.get("diagnostic_attempts",[])
req(len(attempts)==3 and [x.get("ordinal") for x in attempts]==[1,2,3] and all(x.get("status")=="INFRA_INVALID" for x in attempts),"Round23 invalid attempt ledger")
req(attempts[0].get("workflow_run")==36279506026 and attempts[0].get("job_id")==108508563238 and attempts[0].get("artifact_id")==10918841412,"Round23 invalid attempt evidence")
req(attempts[0].get("artifact_sha256")=="14093d80dd902ea003ddf26f46c194b6b9cafdc48391440044fb2b53b7783b8c","Round23 invalid attempt digest")
req(attempts[0].get("failed_stage")=="stage-inputs" and attempts[0].get("package_attempted") is False and attempts[0].get("canonical_state_effect")=="none" and attempts[0].get("usable_for_kio_diagnostic_conclusion") is False,"Round23 invalid attempt1 semantics")
req(attempts[1].get("workflow_run")==36279908858 and attempts[1].get("job_id")==108509683175 and attempts[1].get("artifact_id")==10918078631,"Round23 invalid attempt2 evidence")
req(attempts[1].get("artifact_sha256")=="adb866de60351fa0cb104b3f10187df1532863af639a2ae1227367ae32e5e19f","Round23 invalid attempt2 digest")
req(attempts[1].get("failed_stage")=="source-extract" and attempts[1].get("package_attempted") is False and attempts[1].get("canonical_state_effect")=="none" and attempts[1].get("usable_for_kio_diagnostic_conclusion") is False,"Round23 invalid attempt2 semantics")
req(attempts[2].get("workflow_run")==36280922944 and attempts[2].get("job_id")==108512470733 and attempts[2].get("artifact_status")=="not-produced","Round23 invalid attempt3 evidence")
req(attempts[2].get("failed_stage")=="initialization" and attempts[2].get("package_attempted") is False and attempts[2].get("canonical_state_effect")=="none" and attempts[2].get("usable_for_kio_diagnostic_conclusion") is False,"Round23 invalid attempt3 semantics")
req(M.get("canonical_snapshot")=="12 PASS / 1 pending / 1 current FAIL / 6 BLOCKED","Round23 snapshot")
p=M.get("predecessor_round22",{})
req(R22.get("status")=="diagnostic-PASS" and R22.get("next_gate")=="tier3-round23-kio-krecent-attempt8-rootfs-diagnostic-definition","Round22 handoff")
req(p.get("workflow_run")==36278019755 and p.get("artifact_id")==10917842068 and p.get("conclusion")=="krecentdocument-attempt8-failure-not-reproduced-outside-sbuild","Round23 predecessor")
a=M.get("attempt8_reference",{})
req(a.get("rootfs_artifact_id")==10904512642 and a.get("rootfs_artifact_sha256")=="d689f1658d37e3dedcf57d7f4a233917a6d84ed592346d4ac87f60d626724afe","Round23 exact Attempt8 rootfs")
req(a.get("source_path")=="/build/reproducible-path/kf6-kio-6.30.0" and a.get("home").endswith("/debian/.supralinux-test-home/sbuild"),"Round23 exact paths")
vc=M.get("validity_contract",{})
req(vc.get("exact_attempt8_rootfs_artifact_required") is True and vc.get("package_artifacts_forbidden") is True and vc.get("configure_and_build_without_dpkg_buildpackage") is True,"Round23 validity")
req(vc.get("exact_sbuild_unshare_backend_required") is True and vc.get("manual_chroot_emulation_forbidden") is True and vc.get("starting_build_hook_must_abort_before_dpkg_buildpackage") is True and vc.get("sbuild_build_user_must_be_native_default") is True,"Round23 sbuild containment")
mx=M.get("diagnostic_matrix",[])
req([(x.get("id"),x.get("repetitions")) for x in mx]==[("isolated-krecent",100),("prefix-through-krecent",30),("full-suite",3)],"Round23 matrix")
policy=T.get("discovery_policy",{})
req(policy.get("phase")=="diagnostic" and policy.get("package_builds")=="tier3-round23-diagnostic-pending","Round23 live phase")
req(policy.get("remediation")=="round23-kio-krecent-attempt8-rootfs-diagnostic-pending-ci","Round23 marker")
gate="tier3-round23-kio-krecent-attempt8-rootfs-diagnostic-evidence"
for obj,name in ((T.get("active_remediation",{}),"canonical"),(L.get("active_remediation",{}),"Level1"),(C.get("active_remediation",{}),"contracts"),(MAT.get("active_remediation",{}),"materialization")):
    req(obj.get("next_gate")==gate,name+" Round23 gate")
req(T.get("active_remediation",{}).get("execution_authorized") is False and L.get("execution_authorized") is False and L.get("current_attempt")==8,"Attempt9 remains unauthorized")
req("workflow_call" in W and "pull_request:" not in W,"Round23 reusable-only workflow")
for token in ("run_round23","kde-tier3-kio-round23-diagnostic.yml","tier3-round23-diagnostic-pending"): req(token in ROUTER,"Round23 router "+token)
for token in ("10904512642","--chroot-mode=unshare","starting-build-commands","Command: dpkg-buildpackage","hook-complete","0.91.2ubuntu3",".cache/sbuild","resolute-amd64.tar"): req(token in RUNNER,"Round23 runner "+token)
for token in ("isolated-krecent","prefix-through-krecent","full-suite","override_dh_auto_build","SUPRALINUX_CAPTURE_XBEL","/build/reproducible-path/kf6-kio-6.30.0","runuser -p -u sbuild"): req(token in HOOK,"Round23 hook "+token)
req("useradd" not in RUNNER and "useradd" not in HOOK,"Round23 must not emulate sbuild account")
req("dpkg-buildpackage" in RUNNER,"Round23 explicit package-build prevention guard")
req('--chroot="${ROOTFS_TAR}"' not in RUNNER,"Round23 must use proven unshare cache rootfs selection")
req("Attempt 8 rootfs" in DOC and "Attempt 9" in DOC,"Round23 docs")
req(M.get("next_gate")==gate and M.get("stable_promotion_requires_explicit_user_approval") is True,"Round23 gate/stable")
print("KDE Tier 3 KIO Round 23 diagnostic definition: PASS")
print("rootfs_artifact=10904512642")
print("Attempt9=NOT-AUTHORIZED")
