#!/usr/bin/env python3
from pathlib import Path
import json,subprocess,sys
ROOT=Path(__file__).resolve().parents[1]
def load(p): return json.loads((ROOT/p).read_text())
def req(v,m):
    if not v:
        print("ERROR:",m,file=sys.stderr); raise SystemExit(1)
M=load("manifests/kde-tier3-kio-attempt9-remediation.json")
R26=load("manifests/kde-tier3-kio-round26-remediation.json")
DOC=(ROOT/"docs/kde-tier3-kio-attempt9-remediation.md").read_text()
req(M.get("schema")==1 and M.get("node")=="kio" and M.get("attempt")==9,"Attempt9 identity")
req(M.get("candidate_package_version")=="6.30.0-0supralinux9" and M.get("previous_package_version")=="6.30.0-0supralinux8","Attempt9 version identity")
req(subprocess.run(["dpkg","--compare-versions","6.30.0-0supralinux9","gt","6.30.0-0supralinux8"]).returncode==0,"Attempt9 Debian version must increase")
req(M.get("package_revision_bump_required") is True and M.get("source_rematerialization_required") is True,"Attempt9 source/revision policy")
req(M.get("canonical_kio_state")=="FAIL" and M.get("canonical_snapshot")=="12 PASS / 1 pending / 1 current FAIL / 6 BLOCKED","Attempt9 definition snapshot")
dc=M.get("definition_contract",{})
req(dc.get("status")=="PASS","Attempt9 historical definition contract")
req(dc.get("definition_commit")=="ae542941d035fd7359ca3d616aa38e809f6a6d2f","Attempt9 definition commit")
req(dc.get("validation_commit")=="0997aa320e2d0a7bbf96cce36ce759cd8433f9b4" and dc.get("repository_policy_workflow_run")==36413768747,"Attempt9 definition validation")
req(dc.get("candidate_package_version")=="6.30.0-0supralinux9","Attempt9 historical candidate")
req(dc.get("materialization_authorized_at_definition") is True and dc.get("package_execution_authorized_at_definition") is False,"Attempt9 historical authorization boundary")
req(dc.get("exact_krecent_patch_sha256")=="8718c28a240e5cd5700fff23afe9c122d3f632b80e6db5cde83bcee7e631c602","Attempt9 historical patch")
req(dc.get("exact_patched_source_sha256")=="57d20f3786220178316b31819ba266432207b1f4d55859ccf8d1fad37645021b","Attempt9 historical source")
req(dc.get("visible_test_home")=="debian/supralinux-test-home/sbuild","Attempt9 historical HOME")
req(R26.get("status")=="remediation-PASS","Round26 predecessor")
r=R26.get("result",{})
req(r.get("combined_suite_pass") is True and r.get("candidate_patch_sha256")==dc.get("exact_krecent_patch_sha256") and r.get("candidate_source_sha256")==dc.get("exact_patched_source_sha256"),"Round26 exact candidate provenance")
src=M.get("source_remediation",{})
req(src.get("patch_name")=="supralinux-krecent-deterministic-ordering.patch" and src.get("exact_patch_sha256")==dc.get("exact_krecent_patch_sha256") and src.get("exact_patched_source_sha256")==dc.get("exact_patched_source_sha256"),"Attempt9 source contract")
req(src.get("public_api_change") is False and src.get("abi_change") is False and src.get("xbel_schema_change") is False and src.get("timestamp_format_change") is False,"Attempt9 compatibility shape")
env=M.get("test_environment_remediation",{})
req(env.get("previous_home")=="debian/.supralinux-test-home/sbuild" and env.get("selected_home")=="debian/supralinux-test-home/sbuild","Attempt9 HOME contract")
req(env.get("test_environment_only") is True and env.get("package_runtime_effect") is False and env.get("upstream_tests_filtered") is False and env.get("failures_fatal") is True,"Attempt9 test boundary")
scope=M.get("build_scope",{})
req(scope.get("source_materialization_nodes")==["kio"] and scope.get("retained_revalidation_nodes")==["kxmlgui"] and scope.get("full_level1_rerun_required") is True,"Attempt9 build scope")
req("Definition contract: **PASS**" in DOC and "6.30.0-0supralinux9" in DOC,"Attempt9 docs preserve definition")
print("KDE Tier 3 KIO Attempt 9 historical definition contract: PASS")
