#!/usr/bin/env python3
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]; errors=[]
def req(v,m):
    if not v: errors.append(m)
def load(p): return json.loads((ROOT/p).read_text())
t=load("manifests/kde-frameworks-tier3.json"); c=load("manifests/kde-tier3-package-contracts.json"); m=load("manifests/kde-tier3-materialization.json"); l=load("manifests/kde-tier3-build-level2.json"); a=load("manifests/kde-tier3-build-level2-attempts.json")
r=t.get("level2_remediation",{})
req(r.get("status")=="materialization-pending-ci","Level2 remediation status")
req(r.get("trigger")=={"attempt":3,"workflow_run":36461187872,"commit":"76bbe36b1d036b31bc95840dbba26dbf8e9b0bb1","result":"MIXED"},"Attempt3 trigger")
req(r.get("source_materialization_nodes")==["kcmutils","kparts"] and r.get("retained_source_nodes")==["baloo","knotifyconfig"],"Level2 remediation scope")
req(r.get("candidate_package_versions")=={"kcmutils":"6.30.0-0supralinux2","kparts":"6.30.0-0supralinux2"},"Level2 remediation revisions")
req(r.get("execution_authorized") is False and r.get("canonical_state_effect")=="none","Level2 execution pause")
req(t.get("discovery_policy",{}).get("phase")=="build-level2-remediation-planning","Level2 live phase")
req(t.get("discovery_policy",{}).get("package_builds")=="tier3-level2-attempt3-closed-MIXED-pending-materialization","Level2 build gate")
live=t.get("level2_execution",{})
req(live.get("status")=="attempt3-closed-MIXED-pending-attempt4-materialization" and live.get("execution_authorized") is False,"Attempt3 closure/live pause")
req(live.get("current_attempt")==3 and live.get("next_attempt")==4 and live.get("next_gate")=="tier3-level2-attempt4-remediation-materialization-evidence","Attempt4 handoff")
req(live.get("canonical_snapshot")=="13 PASS / 0 pending / 4 current FAIL / 3 BLOCKED","canonical snapshot")
nodes={x["id"]:x for x in t.get("nodes",[])}
for x in ("baloo","kcmutils","knotifyconfig","kparts"): req(nodes[x].get("state")=="FAIL" and nodes[x].get("packaging",{}).get("state")=="FAIL",x+": canonical FAIL retained")
req(nodes["knewstuff"].get("state")=="BLOCKED" and nodes["knewstuff"].get("packaging",{}).get("blocked_by")==["kcmutils"],"KNewStuff BLOCKED")
req(nodes["ktexteditor"].get("state")=="BLOCKED" and nodes["ktexteditor"].get("packaging",{}).get("blocked_by")==["kparts"],"KTextEditor BLOCKED")
req(nodes["purpose"].get("state")=="BLOCKED" and nodes["purpose"].get("packaging",{}).get("blocked_by")==["kcmutils"],"Purpose BLOCKED")
req(l.get("state")=="remediation-pending-materialization" and l.get("execution_authorized") is False,"Level2 build paused")
s=l.get("attempt3_summary",{})
req(s.get("workflow_run")==36461187872 and s.get("result")=="MIXED","Attempt3 summary")
req(s.get("primary_classification")=={"FAIL":["kcmutils"],"INFRA_INVALID":["baloo","knotifyconfig","kparts"]},"Attempt3 classification")
hist=a.get("campaign_history",[])
req(len(hist)==3 and hist[-1].get("attempt")==3 and hist[-1].get("result")=="MIXED","Attempt3 campaign ledger")
for x in ("baloo","kcmutils","knotifyconfig","kparts"): req(len(a.get("nodes",{}).get(x,[]))==3 and a["nodes"][x][-1].get("package_attempted") is True,x+": Attempt3 ledger")
req(a["nodes"]["kcmutils"][-1].get("result")=="FAIL" and a["nodes"]["kcmutils"][-1].get("stage")=="sbuild" and a["nodes"]["kcmutils"][-1].get("exit_code")==2,"KCMUtils real FAIL")
for x in ("baloo","knotifyconfig","kparts"): req(a["nodes"][x][-1].get("result")=="INFRA_INVALID" and a["nodes"][x][-1].get("stage")=="buildinfo-predecessor-proof",x+": invalid proof")
req(m.get("state")=="remediation-pending-ci" and m.get("remediation_queue")==["kcmutils","kparts"],"materialization queue")
for x in m.get("selected_nodes",[]):
    req(m["nodes"][x].get("state")==("remediation-pending" if x in {"kcmutils","kparts"} else "materialized"),x+": materialization state")
cr=c.get("level2_remediation",{})
req(cr.get("materialization_authorized") is True and cr.get("package_build_authorized") is False,"contract materialization gate")
req(c["nodes"]["kcmutils"].get("package_version_candidate")=="6.30.0-0supralinux2","KCMUtils revision")
kov=c["nodes"]["kcmutils"].get("symbol_template_overrides",[])
req(len(kov)==1 and kov[0].get("package")=="libkf6kcmutilsquick6" and kov[0].get("preserve_tags")==["arch=!riscv64"] and kov[0].get("add_tags")==["optional"],"KCMUtils symbols remediation")
req(c["nodes"]["kparts"].get("package_version_candidate")=="6.30.0-0supralinux2","KParts revision")
adds=c["nodes"]["kparts"].get("symbol_template_additions",[])
req(len(adds)==1 and adds[0].get("package")=="libkf6parts6" and adds[0].get("soname")=="libKF6Parts.so.6" and adds[0].get("symbol")=="_ZSt19piecewise_construct@Base" and adds[0].get("minimal_version")=="6.30.0" and adds[0].get("tags")==["optional"],"KParts symbols remediation")
runner=(ROOT/"scripts/run-kde-tier3-build-level2.sh").read_text()
req("support-closure.json" in runner and '"support_input_ids"' in runner,"support closure proof")
req('if x["kind"]=="support" and x.get("dev_package")' not in runner,"no synthetic support dev buildinfo edge")
if errors:
    for e in errors: print("ERROR:",e,file=sys.stderr)
    raise SystemExit(1)
print("KDE Tier 3 Level 2 Attempt 3 closure/remediation: PASS")
print("canonical=13 PASS / 0 pending / 4 current FAIL / 3 BLOCKED")
print("materialization_queue=kcmutils,kparts")
